# Generated by Django 5.2.4 on 2025-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_project_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address - must be unique', max_length=254, unique=True),
        ),
    ]
