# Generated by Django 5.2.4 on 2025-08-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cleanup_duplicate_time_entries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='hourentry',
            unique_together={('user', 'project', 'date')},
        ),
    ]
