# Generated by Django 5.2.4 on 2025-08-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prevent_duplicate_time_entries'),
        ('core', '0006_prevent_duplicate_time_entries'),
    ]

    operations = [
    ]
